[package]
name = "host-zkm"
version = "0.1.0"
edition = "2021"

[dependencies]
zkm-sdk = { path = "../sdk", features = ["snark"] }
aws-sdk-s3 = "=1.68.0"
bincode = "1.3.3"

tokio = { version = "1.21.0", features = ["macros", "rt-multi-thread", "signal"] }

log = { version = "0.4.14", default-features = false }
env_logger = "0.10.0"
anyhow = "1.0.75"

zkvms_host_io = { path = "../../../zkvms_host_io" }
