[package]
name = "host-nexus"
version = "0.1.0"
edition = "2021"

[dependencies]
nexus-sdk = { path = "/nix/store/fbhw5gcxvvhnz6s0ns1sx4l8n0v8ngi7-Nexus-zkVM-unstable-2025-03-11/sdk" }

zkvms_host_io = { path = "../../../zkvms_host_io" }
