[package]
name = "guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
zkm-runtime = { path = "/nix/store/h9s6kmnx7iafllv10wqhjix5kpyfsh37-zkm-unstable-2025-01-05/runtime/entrypoint" }

wrapper_macro = { version = "0.1.0", path = "../wrapper_macro" }
