[package]
name = "wrapper_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
jolt-sdk-macros = { path = "/nix/store/zgrhjdmxaijxw6kx6b0k2yxigrrb3f94-jolt-unstable-2025-03-12/jolt-sdk/macros" }
proc-macro2 = "1.0.93"
quote = "1.0.38"
