[package]
name = "wrapper_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
jolt-sdk-macros = { path = "/nix/store/p3h58kfgv7c7c5gl9m9hzahzn7dn7xja-jolt-unstable-2025-02-12/jolt-sdk/macros" }
proc-macro2 = "1.0.93"
quote = "1.0.38"
