[package]
name = "wrapper_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
jolt-sdk-macros = { path = "/nix/store/q8ix3vj7dw6w57zhjc9wa38vicymql0g-jolt-unstable-2024-12-18/jolt-sdk/macros" }
proc-macro2 = "1.0.93"
quote = "1.0.38"
