[package]
name = "host-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = { path = "/nix/store/ixfkvjc23xwr9xgnzl4hwd089vbfh4ys-sp1-unstable-2025-02-09/crates/sdk" }

zkvms_host_io = { path = "../../../zkvms_host_io" }
