[package]
name = "host-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = { path = "/nix/store/4837dcscbprhym5gmg97s6ar0f76i550-sp1-unstable-2025-03-10/crates/sdk" }

zkvms_host_io = { path = "../../../zkvms_host_io" }
